---
- name: fact storage_pool_path_correct
  shell: virsh pool-dumpxml default | grep '<path>{{ storage_pool_path }}</path>'
  register: storage_pool_path_correct
  changed_when: false
  failed_when: false

- name: Create storage pool path
  file: state=directory path={{ storage_pool_path }}

- name: Destroy default pool
  shell: virsh pool-destroy default
  when: storage_pool_path_correct.rc != 0
  failed_when: false

- name: Undefine default pool
  shell: virsh pool-undefine default
  when: storage_pool_path_correct.rc != 0
  failed_when: false

- name: Re-create default pool
  shell: virsh pool-define-as default dir --target {{ storage_pool_path }}
  when: storage_pool_path_correct.rc != 0

- name: Start default pool
  shell: virsh pool-start default
  when: storage_pool_path_correct.rc != 0

- name: Set default pool to autostart
  shell: virsh pool-autostart default
  when: storage_pool_path_correct.rc != 0
