---
- name: install rejviz build deps
  yum: name={{ item }} state=present
  with_items:
    - gcc
    - python-devel
    - python-pip
    - libguestfs-tools
    - libvirt-devel
    - virt-install

- name: fact rejviz_installed
  shell: pip list | grep rejviz
  register: rejviz_installed
  changed_when: false
  failed_when: false

- name: install rejviz
  shell: pip install rejviz
  when: rejviz_installed.rc != 0
