---
- name: fact sp1m_image_present
  shell: ls /home/vm_storage_pool/c6-sp1m.qcow2
  register: sp1m_image_present
  changed_when: false
  failed_when: false

- name: copy built image to sp1m
  shell: cp /home/vm_storage_pool/c6-sp1m.qcow2.built /home/vm_storage_pool/c6-sp1m.qcow2
  when: sp1m_image_present.rc != 0

- name: create sp1m vm
  shell: >-
    rejviz-install --noautoconsole --name c6-sp1m
    --memory 2048 --vcpus 1
    --import --disk /home/vm_storage_pool/c6-sp1m.qcow2
    --video qxl --channel spicevmc,target_type=virtio --graphics spice
    --auto-nic-mappings
    --noreboot
  when: sp1m_image_present.rc != 0

- name: start sp1m vm
  shell: virsh start c6-sp1m
  when: sp1m_image_present.rc != 0

- name: wait for sp1m to come up
  wait_for: port=22 host="192.168.130.5" search_regex=OpenSSH delay=10
